# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://moredodo.github.io
date_format: "ordinal"
title: 上海摩铎科技有限公司 
subtitle: ""
description: "上海摩铎科技有限公司"
keywords: 上海摩铎, moredodo
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 上海摩铎科技有限公司 
organization: MoreDoDo
organization_url: https://www.moredodo.com
#github_username: moredodo 
location: Shanghai, China
email: moredodo@icloud.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: moredodo/moredodo.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: moredodo 
    repo: blog-comments
    oauth:
        client_id: 44330218ededf7a030b1 
        client_secret: dce254e97220e4b414ce86bfdf4ab7914e611bbd 
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: moredodo 
    repo: blog-comments
    clientID: 44330218ededf7a030b1
    clientSecret: dce254e97220e4b414ce86bfdf4ab7914e611bbd
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
